### ISSUE TITLE
afl++

### ISSUE THREAD

**Issue by vanhauser-thc** [andreafioraldi/afl#1]
I incorporated your qemu 3.1 patches into afl++ and added the community patches into it. 
Feel free to grab the PPC and ARM fixes and new features into your version.
You can also join the afl++ repository if you want, I can add you as a co-maintainer.

https://github.com/vanhauser-thc/AFLplusplus

**Comment by andreafioraldi** [comment]
Hi, be aware that this patch add a call to afl_maybe_log overhead respect to the inlined patch of abiondo. If the fuzzed application is not multithread then this version is not convenient. The abiondo version is faster but thread-unsafe.

**Comment by andreafioraldi** [comment]
Regards correctness it should be fine, I'm using this patch in a AFL-derivate fuzzer without stability problems.

**Comment by vanhauser-thc** [comment]
I think a version that is threadsafe is better. it works for 100% of the use cases. if someone knows its singe threaded then he can use the original afl and the afl-patches patch that add abiondo's enhancements.

if you want to continue working on the qemu patches at the afl++ repository I can add you as a maintainer, otherwise I will port them over if your make updates.

**Comment by vanhauser-thc** [comment]
great work by the way!

**Comment by andreafioraldi** [comment]
Yes you can add me, I will push updates to the qemu instrumentation directly in your repo
